services:
  db:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dino
    healthcheck:
      test: pg_isready --dbname=db
      interval: 2s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  api:
    build: api
    ports:
      - 3000:3000
    volumes:
      - ./api:/app
    depends_on:
      db:
        condition: service_healthy
