services:
  db:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: dinomalin
      POSTGRES_PASSWORD: dino

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
