name: Tests API

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  tests:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Create secrets
      run: make secrets

    - name: API tests
      run: make tests
